[Telegram]
BOT_TOKEN=seu_bot_token_aqui
# Insira os IDs separados por vírgula
CHAT_IDS=12345678, 87654321

[Monitor]
# Tempo de rotação e verificação em horas (pode usar decimais, ex: 0.5 para 30 min)
CHECK_INTERVAL_HOURS=4

[Email]
# Deixe em branco ou comente as linhas se não quiser usar e-mail em algum servidor
SMTP_SERVER=smtp.seuservidor.com
SMTP_PORT=587
SMTP_USER=alerta@seuservidor.com
SMTP_PASS=sua_senha_segura
SENDER_EMAIL=alerta@seuservidor.com
# Insira os e-mails destinatários separados por vírgula
RECIPIENT_EMAILS=admin@seuservidor.com, suporte@seuservidor.com
