[Telegram]
BOT_TOKEN=seu_bot_token_aqui
# Insira os IDs separados por vírgula
CHAT_IDS=12345678, 87654321

[Monitor]
# Tempo de rotação e verificação em horas (pode usar decimais, ex: 0.5 para 30 min)
CHECK_INTERVAL_HOURS=4
